# Generated by Django 3.2.4 on 2021-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlighter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='media'),
        ),
    ]
